
server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/checklistdb
    username: postgres
    password: julia2017
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: checklist-vehicle

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
